@url = http://localhost:3000
@deletepost = 6599a50d209525216bda6e40
### 
//Return blog posts
GET  {{url}}/api/v1/posts HTTP/1.1
### 
//Add new post
POST {{url}}/api/v1/posts HTTP/1.1
Content-Type: application/json

{
    "title": "Post 1",
    "description": "first post",
    "author": "Cyril",
    "published": true
    
}
### 
//Add new post Curl...
curl -X POST \
  http://localhost:3000/api/v1/posts \
  -H 'Content-Type: application/json' \
  -d '{
    "title": "Post 1",
    "description": "first post",
    "author": "Cyril",
    "published": true
}'

###
//Delete
DELETE {{url}}/api/v1/posts/{{deletepost}} HTTP/1.1
